import type { ChatMessage, Conversation, GroupChatMessage, Student, StudyGroup } from "./types";

export const DEMO_SCHOOL = "Pacific Crest University";

export function getStudentById(id: string): Student | undefined {
  return mockStudents.find((s) => s.id === id);
}

export function getStudyGroupById(id: string, extraGroups: StudyGroup[] = []): StudyGroup | undefined {
  return [...extraGroups, ...mockStudyGroups].find((g) => g.id === id);
}

/** Curated avatar photos — diverse, neutral stock portraits */
function av(seed: string) {
  return `https://images.unsplash.com/${seed}?w=200&h=200&fit=crop&crop=faces`;
}

export const mockStudents: Student[] = [
  {
    id: "s1",
    name: "Jordan Lee",
    avatarUrl: av("photo-1560250097-0b93528c311a"),
    major: "Computer Science",
    year: "Sophomore",
    school: DEMO_SCHOOL,
    bio: "CS tutor in training. I learn best by walking through proofs and pair programming on small problems.",
    classes: ["CSEN 12", "Calculus II", "Physics 1"],
    exams: [{ name: "CSEN 12 Midterm", dateLabel: "Apr 2" }],
    studyGoals: ["Ace CSEN 12", "Stay ahead on p-sets"],
    interests: ["Hackathons", "Coffee shops", "Chess"],
    studyStyle: "problem-solving",
    availability: ["Mon/Wed evenings", "Sat mornings"],
    meetingFormat: "either",
    lookingFor: "both",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s2",
    name: "Amelia Santos",
    avatarUrl: av("photo-1573496359142-b8d87734a5a2"),
    major: "Psychology",
    year: "Junior",
    school: DEMO_SCHOOL,
    bio: "Pre-clinical track. Love turning lecture slides into quiz questions and running through flashcards.",
    classes: ["Intro to Psychology", "Statistics", "Writing Seminar"],
    exams: [{ name: "Stats Midterm", dateLabel: "Mar 31" }],
    studyGoals: ["Memorize terminology", "Practice short answers"],
    interests: ["Running", "Podcasts", "Campus radio"],
    studyStyle: "discussion",
    availability: ["Tue/Thu afternoons", "Sun late afternoon"],
    meetingFormat: "in-person",
    lookingFor: "group",
    activeThisWeek: true,
    lookingThisWeek: false,
  },
  {
    id: "s3",
    name: "Marcus Webb",
    avatarUrl: av("photo-1472099645785-5658abf4ff4e"),
    major: "Mechanical Engineering",
    year: "Senior",
    school: DEMO_SCHOOL,
    bio: "Formula team member. Prefer whiteboards and grinding practice exams with a timer.",
    classes: ["Physics 1", "Calculus I", "Thermodynamics"],
    exams: [{ name: "Physics 1 Exam 2", dateLabel: "Apr 5" }],
    studyGoals: ["Solidify kinematics", "Reduce silly errors"],
    interests: ["Cycling", "CAD", "Jazz"],
    studyStyle: "problem-solving",
    availability: ["Weeknights after 7", "Fri library blocks"],
    meetingFormat: "in-person",
    lookingFor: "partner",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s4",
    name: "Priya Nair",
    avatarUrl: av("photo-1580489944761-15a19acf08f3"),
    major: "Economics",
    year: "Sophomore",
    school: DEMO_SCHOOL,
    bio: "Trying to bridge intuition and math. Happy to explain graphs slowly and trade practice problem sets.",
    classes: ["Economics", "Calculus I", "Writing Seminar"],
    exams: [{ name: "Econ Midterm", dateLabel: "Apr 1" }],
    studyGoals: ["Master supply/demand edge cases", "Graph faster"],
    interests: ["Debate", "Baking", "Student gov"],
    studyStyle: "discussion",
    availability: ["Mon/Wed lunch", "Thu evenings"],
    meetingFormat: "either",
    lookingFor: "both",
    activeThisWeek: false,
    lookingThisWeek: true,
  },
  {
    id: "s5",
    name: "Ethan Park",
    avatarUrl: av("photo-1519085360753-af0119f7cbe7"),
    major: "Computer Science",
    year: "Junior",
    school: DEMO_SCHOOL,
    bio: "Teaching assistant for intro CS. I like quiet library sessions with occasional breaks.",
    classes: ["CSEN 12", "Algorithms", "Discrete Math"],
    exams: [{ name: "CSEN 12 Midterm", dateLabel: "Apr 2" }],
    studyGoals: ["Review recursion", "Mock interview-style drills"],
    interests: ["Open source", "Climbing", "Film"],
    studyStyle: "quiet",
    availability: ["Tue/Thu mornings", "Sun all day"],
    meetingFormat: "virtual",
    lookingFor: "partner",
    activeThisWeek: true,
    lookingThisWeek: false,
  },
  {
    id: "s6",
    name: "Nina Okonkwo",
    avatarUrl: av("photo-1531123897727-8f129e1688ce"),
    major: "Biology",
    year: "Freshman",
    school: DEMO_SCHOOL,
    bio: "First year — still figuring out study routines. Would love an accountability buddy for weekly goals.",
    classes: ["Intro to Psychology", "Chemistry", "Calculus I"],
    exams: [{ name: "Chem Unit Test", dateLabel: "Apr 8" }],
    studyGoals: ["Keep up with lab reports", "Active recall for chem"],
    interests: ["Soccer", "Sketching", "Thriller novels"],
    studyStyle: "accountability",
    availability: ["Afternoons M-F", "Sat brunch study"],
    meetingFormat: "either",
    lookingFor: "partner",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s7",
    name: "Diego Alvarez",
    avatarUrl: av("photo-1507003211169-0a1dd7228f2d"),
    major: "Physics",
    year: "Sophomore",
    school: DEMO_SCHOOL,
    bio: "I narrate my problem-solving out loud — weird but it works. Happy to host small groups in the STEM lounge.",
    classes: ["Physics 1", "Calculus II", "CSEN 12"],
    exams: [{ name: "Physics 1 Exam 2", dateLabel: "Apr 5" }],
    studyGoals: ["Vectors without fear", "P-set speedrun"],
    interests: ["Telescope nights", "Piano", "Hiking"],
    studyStyle: "discussion",
    availability: ["Evenings", "Weekend afternoons"],
    meetingFormat: "in-person",
    lookingFor: "group",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s8",
    name: "Hannah Brooks",
    avatarUrl: av("photo-1438761681033-6461ffad8d80"),
    major: "English",
    year: "Senior",
    school: DEMO_SCHOOL,
    bio: "Thesis on modern essayists. I thrive on peer feedback loops for drafts and thesis statements.",
    classes: ["Writing Seminar", "Literary Theory", "Economics"],
    exams: [{ name: "Lit Theory Take-home", dateLabel: "Apr 12" }],
    studyGoals: ["Tighten argument structure", "Citation cleanup"],
    interests: ["Zines", "Indie bookstores", "Swimming"],
    studyStyle: "discussion",
    availability: ["Wed/Fri mornings", "Sun evenings"],
    meetingFormat: "either",
    lookingFor: "partner",
    activeThisWeek: false,
    lookingThisWeek: false,
  },
  {
    id: "s9",
    name: "Sam Rivera",
    avatarUrl: av("photo-1500648767791-00dcc994a43e"),
    major: "Computer Science",
    year: "Freshman",
    school: DEMO_SCHOOL,
    bio: "CSEN 12 is my first real coding class. Want someone patient to rubber-duck debugging with.",
    classes: ["CSEN 12", "Calculus I", "Writing Seminar"],
    exams: [{ name: "CSEN 12 Midterm", dateLabel: "Apr 2" }],
    studyGoals: ["Arrays & loops", "Start projects early"],
    interests: ["Esports", "K-pop dance", "Matcha"],
    studyStyle: "problem-solving",
    availability: ["Late nights", "Sat/Sun flex"],
    meetingFormat: "virtual",
    lookingFor: "both",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s10",
    name: "Taylor Chen",
    avatarUrl: av("photo-1494790108377-be9c29b29330"),
    major: "Cognitive Science",
    year: "Junior",
    school: DEMO_SCHOOL,
    bio: "Bridge between psych and CS. I make Anki decks and share them — ask me for my Intro Psych set.",
    classes: ["Intro to Psychology", "CSEN 12", "Statistics"],
    exams: [{ name: "Intro Psych Midterm", dateLabel: "Mar 29" }],
    studyGoals: ["Memory & consolidation unit", "Stats hypothesis tests"],
    interests: ["UX research", "Rock climbing", "Cooking"],
    studyStyle: "quiet",
    availability: ["Mon/Wed/Fri midday"],
    meetingFormat: "either",
    lookingFor: "group",
    activeThisWeek: true,
    lookingThisWeek: false,
  },
  {
    id: "s11",
    name: "Omar Haddad",
    avatarUrl: av("photo-1506794778202-cad84cf45f1d"),
    major: "Economics",
    year: "Senior",
    school: DEMO_SCHOOL,
    bio: "Internship offer locked — still finishing strong. Prefer 90-minute focused blocks with a clear agenda.",
    classes: ["Econometrics", "Economics", "Calculus II"],
    exams: [{ name: "Metrics Midterm", dateLabel: "Apr 4" }],
    studyGoals: ["OLS intuition", "Stata debugging"],
    interests: ["Soccer", "Arabic poetry", "Stocks"],
    studyStyle: "accountability",
    availability: ["Early mornings", "Sun nights"],
    meetingFormat: "in-person",
    lookingFor: "partner",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s12",
    name: "Riley Kim",
    avatarUrl: av("photo-1544723795-432537d12f56"),
    major: "Mathematics",
    year: "Sophomore",
    school: DEMO_SCHOOL,
    bio: "Problem sets are puzzles. Let's work in parallel and compare solutions.",
    classes: ["Calculus I", "Calculus II", "Physics 1"],
    exams: [{ name: "Calculus I Midterm", dateLabel: "Apr 3" }],
    studyGoals: ["Series & sequences", "Proof writing warmup"],
    interests: ["Puzzle hunts", "Volleyball", "Tea"],
    studyStyle: "problem-solving",
    availability: ["Tue/Thu all day", "Fri evening"],
    meetingFormat: "either",
    lookingFor: "both",
    activeThisWeek: true,
    lookingThisWeek: false,
  },
  {
    id: "s13",
    name: "Camila Fernández",
    avatarUrl: av("photo-1534528741775-53994a69daeb"),
    major: "Psychology",
    year: "Sophomore",
    school: DEMO_SCHOOL,
    bio: "Non-traditional student with a day job on weekends — I batch my study Mon/Tue night.",
    classes: ["Intro to Psychology", "Writing Seminar", "Statistics"],
    exams: [{ name: "Intro Psych Midterm", dateLabel: "Mar 29" }],
    studyGoals: ["Condense chapters to outlines", "Practice FRQs"],
    interests: ["Parenting club", "Photography", "True crime docs"],
    studyStyle: "discussion",
    availability: ["Mon/Tue nights only"],
    meetingFormat: "virtual",
    lookingFor: "group",
    activeThisWeek: false,
    lookingThisWeek: true,
  },
  {
    id: "s14",
    name: "Alex Morgan",
    avatarUrl: av("photo-1508214751196-bcfd4ca60f91"),
    major: "Undeclared",
    year: "Freshman",
    school: DEMO_SCHOOL,
    bio: "Exploring econ vs. public policy. Looking for structured study sessions so I don't procrastinate.",
    classes: ["Economics", "Writing Seminar", "Intro to Psychology"],
    exams: [{ name: "Econ Midterm", dateLabel: "Apr 1" }],
    studyGoals: ["Keep readings current", "Outline every lecture"],
    interests: ["Student newspaper", "Running", "Bread baking"],
    studyStyle: "accountability",
    availability: ["Mornings", "Sun library"],
    meetingFormat: "in-person",
    lookingFor: "partner",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s15",
    name: "Kenji Tanaka",
    avatarUrl: av("photo-1519345182560-3f2917c472ef"),
    major: "Physics",
    year: "Junior",
    school: DEMO_SCHOOL,
    bio: "Lab report stickler. Happy to trade feedback on figures and error propagation.",
    classes: ["Physics 1", "Electronics", "Calculus II"],
    exams: [{ name: "Physics 1 Exam 2", dateLabel: "Apr 5" }],
    studyGoals: ["Labs under 3 hours", "Exam 1 mistakes review"],
    interests: ["Amateur radio", "Sourdough", "Badminton"],
    studyStyle: "quiet",
    availability: ["Weekday evenings"],
    meetingFormat: "either",
    lookingFor: "partner",
    activeThisWeek: true,
    lookingThisWeek: false,
  },
  {
    id: "s16",
    name: "Zoe Patterson",
    avatarUrl: av("photo-1531746020798-e6953c6e8e04"),
    major: "Computer Science",
    year: "Senior",
    school: DEMO_SCHOOL,
    bio: "Capstone-heavy semester. I still want to help underclassmates with CSEN 12 — keeps fundamentals fresh.",
    classes: ["CSEN 12", "Distributed Systems", "Ethics"],
    exams: [{ name: "CSEN 12 Midterm (Grader)", dateLabel: "Apr 2" }],
    studyGoals: ["Office hours prep", "Explain clearly"],
    interests: ["Mentoring", "Indie games", "Trail running"],
    studyStyle: "discussion",
    availability: ["Wed/Fri flex"],
    meetingFormat: "either",
    lookingFor: "group",
    activeThisWeek: false,
    lookingThisWeek: false,
  },
  {
    id: "s17",
    name: "Isaac Okoro",
    avatarUrl: av("photo-1522558635356-49f63efe2b9c"),
    major: "Economics",
    year: "Junior",
    school: DEMO_SCHOOL,
    bio: "Quant-oriented. Bring your practice exams — I'll time us and we review every wrong answer twice.",
    classes: ["Economics", "Statistics", "Calculus I"],
    exams: [{ name: "Econ Midterm", dateLabel: "Apr 1" }],
    studyGoals: ["Game theory basics", "Elasticity drills"],
    interests: ["Chess", "Afrobeats", "Campus investing club"],
    studyStyle: "problem-solving",
    availability: ["Thu/Fri/Sat"],
    meetingFormat: "in-person",
    lookingFor: "both",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s18",
    name: "Mei-Lin Huang",
    avatarUrl: av("photo-1544005313-94ddf0286df2"),
    major: "Biochemistry",
    year: "Sophomore",
    school: DEMO_SCHOOL,
    bio: "Orgo next year scare tactics got to me — trying to build strong chem habits now.",
    classes: ["Chemistry", "Calculus I", "Physics 1"],
    exams: [{ name: "Chem Unit Test", dateLabel: "Apr 8" }],
    studyGoals: ["Mechanisms flashcards", "Dimensional analysis speed"],
    interests: ["Cello", "Powerlifting", "Museum walks"],
    studyStyle: "quiet",
    availability: ["Sun–Tue", "Thu morning"],
    meetingFormat: "either",
    lookingFor: "partner",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s19",
    name: "Chloe Winters",
    avatarUrl: av("photo-1524504388940-b1c1722653e1"),
    major: "English",
    year: "Junior",
    school: DEMO_SCHOOL,
    bio: "Creative non-fiction track. I host quiet writing hours — headphones on, pomodoros, shared goals.",
    classes: ["Writing Seminar", "Poetry Workshop", "Intro to Psychology"],
    exams: [{ name: "Workshop portfolio", dateLabel: "Apr 10" }],
    studyGoals: ["Revise two essays", "Reading responses"],
    interests: ["Letterpress", "Farmers markets", "Swimming"],
    studyStyle: "accountability",
    availability: ["Tue/Thu evenings", "Sat morning"],
    meetingFormat: "in-person",
    lookingFor: "group",
    activeThisWeek: true,
    lookingThisWeek: false,
  },
  {
    id: "s20",
    name: "Ben Carter",
    avatarUrl: av("photo-1566492031773-4f4e44671857"),
    major: "Mechanical Engineering",
    year: "Sophomore",
    school: DEMO_SCHOOL,
    bio: "Transferred last term — still mapping the best study spots. Love grinding physics problem sets.",
    classes: ["Physics 1", "Calculus I", "Graphics"],
    exams: [{ name: "Physics 1 Exam 2", dateLabel: "Apr 5" }],
    studyGoals: ["Catch up on HW 4-6", "Free-body diagrams"],
    interests: ["3D printing", "Pick-up basketball", "Cooking meals for roommates"],
    studyStyle: "problem-solving",
    availability: ["Most evenings"],
    meetingFormat: "either",
    lookingFor: "both",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s21",
    name: "Vivian Osei",
    avatarUrl: av("photo-1520813792240-56fc4a3765a7"),
    major: "Public Health",
    year: "Senior",
    school: DEMO_SCHOOL,
    bio: "Applying to MPH programs. I color-code notes and like co-working blocks with clear start/stop times.",
    classes: ["Statistics", "Intro to Psychology", "Writing Seminar"],
    exams: [{ name: "Stats final prep", dateLabel: "Apr 14" }],
    studyGoals: ["Regression interpretation", "Policy memo draft"],
    interests: ["Community clinic volunteering", "Spoken word", "Yoga"],
    studyStyle: "accountability",
    availability: ["Mon/Thu evenings", "Sun afternoon"],
    meetingFormat: "either",
    lookingFor: "partner",
    activeThisWeek: false,
    lookingThisWeek: true,
  },
  {
    id: "s22",
    name: "Noah Feldman",
    avatarUrl: av("photo-1507591064344-4c6ce005b128"),
    major: "Philosophy",
    year: "Junior",
    school: DEMO_SCHOOL,
    bio: "Logic nerd. Happy to slow-read dense articles and workshop thesis sentences.",
    classes: ["Writing Seminar", "Economics", "Ethics"],
    exams: [{ name: "Logic quiz", dateLabel: "Apr 6" }],
    studyGoals: ["Truth tables speed", "Argument mapping"],
    interests: ["Debate watch parties", "Urban sketching", "Espresso"],
    studyStyle: "discussion",
    availability: ["Midday gaps T/Th", "Fri library"],
    meetingFormat: "in-person",
    lookingFor: "group",
    activeThisWeek: true,
    lookingThisWeek: false,
  },
  {
    id: "s23",
    name: "Sara Abadi",
    avatarUrl: av("photo-1487412720507-e7ab37603c6f"),
    major: "Statistics",
    year: "Sophomore",
    school: DEMO_SCHOOL,
    bio: "Love RStudio and annotated homework keys. Prefer splitting practice sets and comparing answers.",
    classes: ["Statistics", "Calculus II", "Economics"],
    exams: [{ name: "Stats Midterm", dateLabel: "Mar 31" }],
    studyGoals: ["Probability trees", "ggplot polish"],
    interests: ["Data viz", "Crochet", "Intramural soccer"],
    studyStyle: "problem-solving",
    availability: ["Weekday late afternoon"],
    meetingFormat: "virtual",
    lookingFor: "both",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s24",
    name: "Chris Nguyen",
    avatarUrl: av("photo-1599566150163-00194bb0b1c5"),
    major: "Computer Science",
    year: "Senior",
    school: DEMO_SCHOOL,
    bio: "Part-time intern. Still carving time for classmates — async reviews over Discord work best.",
    classes: ["CSEN 12", "Databases", "HCI"],
    exams: [{ name: "HCI prototype deadline", dateLabel: "Apr 9" }],
    studyGoals: ["Ship usable prototype", "User test notes"],
    interests: ["Lo-fi playlists", "Bouldering", "Matcha"],
    studyStyle: "discussion",
    availability: ["Async + Thu night"],
    meetingFormat: "virtual",
    lookingFor: "partner",
    activeThisWeek: true,
    lookingThisWeek: false,
  },
  {
    id: "s25",
    name: "Emily Ross",
    avatarUrl: av("photo-1573497019940-1c28f9d8f33a"),
    major: "Environmental Science",
    year: "Freshman",
    school: DEMO_SCHOOL,
    bio: "Field labs + lectures = busy weeks. Looking for a small group to keep me honest on readings.",
    classes: ["Calculus I", "Intro to Psychology", "Writing Seminar"],
    exams: [{ name: "Ecology quiz", dateLabel: "Apr 7" }],
    studyGoals: ["Catch up on field journal", "Graph interpretation"],
    interests: ["Birding", "Student farm", "Pottery"],
    studyStyle: "discussion",
    availability: ["Sun–Wed evenings"],
    meetingFormat: "in-person",
    lookingFor: "group",
    activeThisWeek: true,
    lookingThisWeek: true,
  },
  {
    id: "s26",
    name: "Daniel Ortiz",
    avatarUrl: av("photo-1463453091185-6620205498cd"),
    major: "Chemistry",
    year: "Junior",
    school: DEMO_SCHOOL,
    bio: "TA for intro lab. I bring old exams (anonymized) and we red-team the rubric.",
    classes: ["Chemistry", "Physics 1", "Calculus II"],
    exams: [{ name: "Chem Unit Test", dateLabel: "Apr 8" }],
    studyGoals: ["IR spectroscopy", "Titration calculations"],
    interests: ["Rock climbing", "Jazz band", "Coffee roasting"],
    studyStyle: "problem-solving",
    availability: ["Mon/Wed/Fri after 4pm"],
    meetingFormat: "either",
    lookingFor: "both",
    activeThisWeek: false,
    lookingThisWeek: false,
  },
];

export const mockStudyGroups: StudyGroup[] = [
  {
    id: "g1",
    title: "CSEN 12 Midterm Review",
    classTag: "CSEN 12",
    memberCount: 6,
    maxMembers: 8,
    nextExam: "CSEN 12 Midterm — Apr 2",
    studyGoal: "Arrays, loops, debugging drills",
    schedule: "Tue & Thu · 7–9pm · Engineering Library Room 204",
    format: "in-person",
  },
  {
    id: "g2",
    title: "Calculus I Problem-Solving Group",
    classTag: "Calculus I",
    memberCount: 4,
    maxMembers: 6,
    nextExam: "Midterm — Apr 3",
    studyGoal: "Limit & continuity marathon",
    schedule: "Sat · 10am–12pm · Zoom",
    format: "virtual",
  },
  {
    id: "g3",
    title: "Physics 1 Weekly Study Session",
    classTag: "Physics 1",
    memberCount: 5,
    maxMembers: 8,
    nextExam: "Exam 2 — Apr 5",
    studyGoal: "Kinematics + energy practice sets",
    schedule: "Wed · 6–8pm · STEM Commons",
    format: "either",
  },
  {
    id: "g4",
    title: "Intro Psych Flashcard Crew",
    classTag: "Intro to Psychology",
    memberCount: 7,
    maxMembers: 10,
    nextExam: "Midterm — Mar 29",
    studyGoal: "Memory & learning unit",
    schedule: "Sun · 3–5pm · Quad study lounge",
    format: "in-person",
  },
  {
    id: "g5",
    title: "Econ Midterm Cohort",
    classTag: "Economics",
    memberCount: 3,
    maxMembers: 5,
    nextExam: "Econ Midterm — Apr 1",
    studyGoal: "Elasticity & surplus drills",
    schedule: "Mon/Wed · 5–6:30pm · Hybrid",
    format: "either",
  },
  {
    id: "g6",
    title: "Writing Seminar Draft Swap",
    classTag: "Writing Seminar",
    memberCount: 4,
    maxMembers: 5,
    nextExam: "Essay 2 due Apr 11",
    studyGoal: "Peer feedback on outlines",
    schedule: "Fri · 2–4pm · Writing Center pods",
    format: "in-person",
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "c1",
    peerId: "s1",
    peerName: "Jordan Lee",
    peerAvatar: av("photo-1560250097-0b93528c311a"),
    lastPreview: "Want to pair on the recursion worksheet tomorrow?",
    unread: 1,
  },
  {
    id: "c2",
    peerId: "s5",
    peerName: "Ethan Park",
    peerAvatar: av("photo-1519085360753-af0119f7cbe7"),
    lastPreview: "I posted my Anki deck in the class folder.",
    unread: 0,
  },
  {
    id: "c3",
    peerId: "s10",
    peerName: "Taylor Chen",
    peerAvatar: av("photo-1494790108377-be9c29b29330"),
    lastPreview: "Library 2nd floor at 3pm still works for you?",
    unread: 0,
  },
];

export const mockInitialMessages: Record<string, ChatMessage[]> = {
  c1: [
    {
      id: "m1",
      conversationId: "c1",
      fromMe: false,
      text: "Hey — saw you're in CSEN 12 too. Want to pair on the recursion worksheet tomorrow?",
      at: "10:12 AM",
    },
    {
      id: "m2",
      conversationId: "c1",
      fromMe: true,
      text: "Yes! I'm free after 4. Library 3rd floor ok?",
      at: "10:14 AM",
    },
    {
      id: "m3",
      conversationId: "c1",
      fromMe: false,
      text: "Perfect. I'll bring scratch paper and we can time ourselves on two medium problems.",
      at: "10:16 AM",
    },
  ],
  c2: [
    {
      id: "m4",
      conversationId: "c2",
      fromMe: false,
      text: "I posted my Anki deck in the class folder — feel free to clone cards.",
      at: "Yesterday",
    },
    {
      id: "m5",
      conversationId: "c2",
      fromMe: true,
      text: "Legend. I'll add a few stats cards and push an update tonight.",
      at: "Yesterday",
    },
  ],
  c3: [
    {
      id: "m6",
      conversationId: "c3",
      fromMe: false,
      text: "Library 2nd floor at 3pm still works for you?",
      at: "Mon",
    },
    {
      id: "m7",
      conversationId: "c3",
      fromMe: true,
      text: "Works great. I'll grab the quiet zone near the windows.",
      at: "Mon",
    },
  ],
};

export const mockGroupMessages: Record<string, GroupChatMessage[]> = {
  g1: [
    {
      id: "gm1",
      groupId: "g1",
      senderName: "Jordan Lee",
      senderAvatar: getStudentById("s1")!.avatarUrl,
      fromMe: false,
      text: "Dropping a recursion cheat sheet before tonight's session.",
      at: "2:11 PM",
    },
    {
      id: "gm2",
      groupId: "g1",
      senderName: "Sam Rivera",
      senderAvatar: getStudentById("s9")!.avatarUrl,
      fromMe: false,
      text: "Can we review pointer logic first? I keep missing edge cases.",
      at: "2:14 PM",
    },
  ],
  g2: [
    {
      id: "gm3",
      groupId: "g2",
      senderName: "Riley Kim",
      senderAvatar: getStudentById("s12")!.avatarUrl,
      fromMe: false,
      text: "Uploading a fresh set of limit problems right now.",
      at: "Yesterday",
    },
  ],
  g3: [
    {
      id: "gm4",
      groupId: "g3",
      senderName: "Diego Alvarez",
      senderAvatar: getStudentById("s7")!.avatarUrl,
      fromMe: false,
      text: "Wednesday session moved to 6:15 so everyone can grab food first.",
      at: "Mon",
    },
  ],
};